name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Naaufal
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Pull latest changes from main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Naaufal/Naaufal.git
          git pull origin main --rebase

      - name: Commit and Push
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "generated snake 🐍" || echo "no changes to commit"
          git push origin main
